In [ ]:
from infection_propagation import Graph
from infection_propagation import Figures
import importlib
import json
import time
importlib.reload(Graph)
importlib.reload(Figures)

# Bidirectional Search Toy, Not Full, Implemented, Sometimes Returns Incorrect Path

- [ ] Look at A* behavior with unadmissable heuristic
- [ ] Look at using dictionary, lazy load matrix/pandas
    - [ ] separate dictionary for storing delays as well as distribution data?
- [ ] Complexity analysis of loading graph data structures

In [44]:
threshold_value = lambda x : np.log(x)/x
n = 1000
p = 1.2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.006907755278982137
P value: 0.008289306334778564

In [36]:
h._adjency_matrix

,12,15,17,20,21,23,24,25,26,27,...,19,2,22,3,39,4,40,5,54,9
0,,,,,,,,,,,,,,,,,,,,,
0,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
10,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
11,inf,inf,inf,inf,inf,<tree_...,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
12,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,inf,...,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,<tree_...,...,inf,inf,<tree_...,inf,<tree_...,inf,inf,inf,inf,<tree_...
96,inf,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,...,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf
97,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
98,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf
99,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [37]:
t0 = time.time()
t = h.simulate_gossip_rv('1', '4')
tf = time.time()
print(t)
print(tf-t0)

0.9862695365662382
0.3527350425720215

In [38]:
h._adjency_matrix

,12,15,17,20,21,23,24,25,26,27,...,19,2,22,3,39,4,40,5,54,9
0,,,,,,,,,,,,,,,,,,,,,
0,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
10,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
11,inf,inf,inf,inf,inf,0.162049,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
12,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,inf,...,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,<tree_...,...,inf,inf,<tree_...,inf,<tree_...,inf,inf,inf,inf,<tree_...
96,inf,inf,inf,inf,inf,inf,inf,inf,<tree_...,inf,...,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf
97,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
98,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf
99,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [46]:
h.sim_all(reset=True)

In [40]:
h._adjency_matrix

,12,15,17,20,21,23,24,25,26,27,...,19,2,22,3,39,4,40,5,54,9
0,,,,,,,,,,,,,,,,,,,,,
0,inf,inf,inf,0.067214,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
10,inf,1.587686,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
11,inf,inf,inf,inf,inf,2.166092,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
12,inf,inf,inf,inf,inf,inf,inf,0.189298,inf,inf,...,inf,inf,inf,0.886595,inf,inf,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,inf,inf,inf,inf,inf,inf,inf,0.867823,inf,0.697756,...,inf,inf,0.447898,inf,3.419012,inf,inf,inf,inf,0.766116
96,inf,inf,inf,inf,inf,inf,inf,inf,0.162012,inf,...,inf,inf,4.33319,inf,inf,inf,inf,inf,inf,inf
97,inf,inf,inf,1.85469,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
98,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,0.213616,inf,inf,inf,inf,inf,inf,inf
99,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [47]:
t0 = time.time()
t = h.algo_jump('1', '4', algorithm="")
tf = time.time()
print(t)
print(tf-t0)

1.4152572774716143
10.973419904708862

In [42]:
h.construct_path('1', '4')

['4', '67', '56', '1']

In [48]:
t0 = time.time()
t = h.algo_jump('1', '4', algorithm="bidir")
tf = time.time()
print(t)
print(tf-t0)

1.4152572774716141
0.6382303237915039

In [32]:
h.construct_path('1','4')

['4', '0', '1']

In [33]:
# How many times will it return the same path?
def accuracy_trial(iters=10**3, edgedst=None):
    blind_times = []
    blind_paths = []
    informed_times = []
    informed_paths = []
    for i in range(iters):
        h = Graph.erdos_renyi(n, p, force_connection=True, edge_dst=edgedst)
        h.sim_all()
        blind_times.append(h.algo_jump('1', '4', algorithm="bidir"))
        p1 = h.construct_path('1','4')
        blind_paths.append(p1)
        informed_times.append(h.algo_jump('1', '4', algorithm=""))
        p2 = h.construct_path('1','4')
        informed_paths.append(p2)
    return blind_times, blind_paths, informed_times, informed_paths

In [34]:
a,b,c,d = accuracy_trial()

In [18]:
b == d

True

# Look at non reversible RV, like a Uniform RV

# Do we need to add auxillary nodes to help the precision on the Dijsktra's path?
- ie we add more "fake observers" that connect to our src and dst subtrees to make a subgraph, and the shortest path we find in this subgraph may likely agree with the shortest path?

https://arxiv.org/pdf/1911.01521`
- first paragraph, note about adjacent matrix, $D(u,w) = D(u,v) - 1)$ or $D(u,w) = D(u,v) + 1$

First start advantage?
- how likely is the first minimal edge on the frontier on the final shortest path?

MOre results
- [X] Can we show dijsktra's shows a similar distribution? 
    - [X] Time dst? 
    - [X] Path Dst?
- [X] Bidirectional is good here right? Adding extra info about new delays doesn't change shortest path right?
    - Yes! Dijsktra's and Blind Search give shortest paths
- [X] At what amound of auxillary nodes is optimal for constraining the graph? How do we find these optimal auxillary nodes?
    - Bidirectional is instance optimal with nodes expanded $O(\Delta G)$, $\Delta G$ is maximal degree of graph

## Instance Optimal? Can not relax fewer edges on the graph asympotically, no need to find "auxillary nodes"

https://arxiv.org/abs/2410.14638
- bidirectional A* is more optimal but we'd need to beable to formulate a heuristic (very difficult)

## Trad Graph

In [14]:
threshold_value = lambda x : np.log(x)/x
n = 10
p = 1.2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.23025850929940458
P value: 0.2763102111592855

In [15]:
h._adjency_matrix

,4,5,6,7,8,9,0,1,2,3
0,,,,,,,,,,
0,inf,inf,<tree_...,<tree_...,<tree_...,<tree_...,inf,inf,inf,inf
1,inf,<tree_...,inf,inf,inf,<tree_...,inf,inf,inf,inf
2,<tree_...,inf,<tree_...,inf,<tree_...,<tree_...,inf,inf,inf,inf
3,<tree_...,inf,inf,inf,inf,inf,inf,inf,inf,inf
4,inf,<tree_...,inf,<tree_...,<tree_...,inf,inf,inf,<tree_...,<tree_...
5,<tree_...,inf,inf,inf,inf,inf,inf,<tree_...,inf,inf
6,inf,inf,inf,inf,<tree_...,inf,<tree_...,inf,<tree_...,inf
7,<tree_...,inf,inf,inf,inf,<tree_...,<tree_...,inf,inf,inf
8,<tree_...,inf,<tree_...,inf,inf,<tree_...,<tree_...,inf,<tree_...,inf
9,inf,inf,inf,<tree_...,<tree_...,inf,<tree_...,<tree_...,<tree_...,inf

In [16]:
t = h.simulate_gossip_rv('1', '4', preserve_times=True)
print(h.construct_path('1','4'))
print(t)

['4', '5', '1']
0.7448095222284945

In [17]:
h._adjency_matrix

,4,5,6,7,8,9,0,1,2,3
0,,,,,,,,,,
0,inf,inf,<tree_...,<tree_...,<tree_...,<tree_...,inf,inf,inf,inf
1,inf,0.128284,inf,inf,inf,1.094388,inf,inf,inf,inf
2,<tree_...,inf,<tree_...,inf,<tree_...,<tree_...,inf,inf,inf,inf
3,<tree_...,inf,inf,inf,inf,inf,inf,inf,inf,inf
4,inf,0.616526,inf,<tree_...,<tree_...,inf,inf,inf,<tree_...,<tree_...
5,0.616526,inf,inf,inf,inf,inf,inf,0.128284,inf,inf
6,inf,inf,inf,inf,<tree_...,inf,<tree_...,inf,<tree_...,inf
7,<tree_...,inf,inf,inf,inf,<tree_...,<tree_...,inf,inf,inf
8,<tree_...,inf,<tree_...,inf,inf,<tree_...,<tree_...,inf,<tree_...,inf
9,inf,inf,inf,<tree_...,<tree_...,inf,<tree_...,1.094388,<tree_...,inf

In [18]:
h.sim_all()
t = h.algo_jump('1', '4', algorithm="")
print(h.construct_path('1','4'))
print(t)

['4', '5', '1']
0.7448095222284945

In [19]:
h._adjency_matrix

,4,5,6,7,8,9,0,1,2,3
0,,,,,,,,,,
0,inf,inf,0.701789,0.195791,0.313861,0.183014,inf,inf,inf,inf
1,inf,0.128284,inf,inf,inf,1.094388,inf,inf,inf,inf
2,1.017619,inf,0.528023,inf,1.967763,0.404443,inf,inf,inf,inf
3,0.009326,inf,inf,inf,inf,inf,inf,inf,inf,inf
4,inf,0.616526,inf,0.805551,2.303117,inf,inf,inf,1.017619,0.009326
5,0.616526,inf,inf,inf,inf,inf,inf,0.128284,inf,inf
6,inf,inf,inf,inf,1.424738,inf,0.701789,inf,0.528023,inf
7,0.805551,inf,inf,inf,inf,0.20784,0.195791,inf,inf,inf
8,2.303117,inf,1.424738,inf,inf,0.414891,0.313861,inf,1.967763,inf
9,inf,inf,inf,0.20784,0.414891,inf,0.183014,1.094388,0.404443,inf

In [ ]:
# How many times will it return the same path?
def accuracy_trial(iters=10**3, edgedst=None):
    blind_times = []
    blind_paths = []
    informed_times = []
    informed_paths = []
    for i in range(iters):
        h = Graph.erdos_renyi(n, p, force_connection=True, edge_dst=edgedst)
        blind_times.append(h.simulate_gossip_rv('1', '4', preserve_times=True))
        p1 = h.construct_path('1','4')
        blind_paths.append(p1)
        h.sim_all()
        informed_times.append(h.algo_jump('1', '4', algorithm=""))
        p2 = h.construct_path('1','4')
        informed_paths.append(p2)
    return blind_times, blind_paths, informed_times, informed_paths

In [22]:
a,b,c,d = accuracy_trial()

In [23]:
set(np.isclose(a,c))

{np.True_}

In [24]:
b == d

True

## Uniform RVs

In [7]:
edge_dst = None
with open('../test_graphs/unit1.json') as json_file:
    edge_dst = json.load(json_file)

In [14]:
threshold_value = lambda x : np.log(x)/x
n = 1000
p = 1.2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True, edge_dst=edge_dst)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.006907755278982137
P value: 0.008289306334778564

In [15]:
h._adjency_matrix

,10,101,103,104,105,106,107,109,110,112,...,75,77,79,8,85,86,87,88,94,97
0,,,,,,,,,,,,,,,,,,,,,
0,inf,<tree_...,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
10,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
100,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
101,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,<tree_...,inf,inf,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
996,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
997,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
998,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
999,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [17]:
h.simulate_gossip_rv('1','6')

0.7164560892766434

In [18]:
h.construct_path('1','6')

['6', '420', '115', '671', '249', '740', '1']

In [26]:
a,b,c,d = accuracy_trial(edgedst=edge_dst)

In [27]:
set(np.isclose(a,c))

{np.True_}

In [28]:
b==d

True

# Fiddling with two different implements of dijkstra's

In [ ]:
threshold_value = lambda x : np.log(x)/x
n = 20
p = 2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.14978661367769955
P value: 0.2995732273553991

In [4]:
t = h.simulate_gossip_rv('1', '4', preserve_times=True)

In [6]:
t1 = h.algo_jump('1', '4', algorithm="")

In [9]:
t== t1

True

In [8]:
t1

0.5142583188609857

In [10]:
h.construct_time_from_path('1', '4')

0.5142583188609857

# Fiddling with two different implements of bi-dijkstra's

In [65]:
threshold_value = lambda x : np.log(x)/x
n = 1000
p = 2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.006907755278982137
P value: 0.013815510557964273

In [66]:
t0 = time.time()
t = h.birectional_simulate_gossip_rv('1', '4')
tf = time.time()
print(t)
print(tf-t0)

0.7406972924596469
1.2847230434417725

In [67]:
h.sim_all()
t0 = time.time()
t = h.algo_jump('1', '4')
tf = time.time()
print(t)
print(tf-t0)

0.7406972924596469
0.6272189617156982